substitutions:
  devicename: water-tank-final
  friendly_name: Water tank and well sensor
  device_description:  Water tank and well sensor (Carat 4m3)

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  comment: ${device_description}

esp32:
  board: lolin_s2_mini #Pinout: https://www.wemos.cc/en/latest/s2/s2_mini.html
  variant: esp32s2
  framework:
    type: arduino

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  

# Enable logging
logger: 
  level: VERBOSE
  baud_rate: 0

captive_portal:

api:
  password: "1234343"

# restart 
button:
  - platform: restart
    name: Restart

sensor:
# Reports how long the device has been powered (in minutes)
  - platform: uptime
    name: Uptime
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes

# water level sensor
# https://esphome.io/components/sensor/modbus_controller.html
  - platform: modbus_controller
    modbus_controller_id: qd
    name: "Water level"
    id: modbus_water_level
    register_type: holding
    address: 0x0004
    unit_of_measurement: "cm"
    value_type: S_WORD
    
  - platform: template
    name: "Water level with NaN"
    lambda: |-
      if (isnan(id(modbus_water_level).state)) {
        return NAN;
      } else {
        return id(modbus_water_level).state;
      }
    update_interval: 5s

    

# Reports the WiFi signal strength
  - platform: wifi_signal
    name: Wifi Signal
    update_interval: 60s

text_sensor:
  - platform: version
    name: ESPHome Version
  - platform: wifi_info
    ip_address: # exposes the IP Address when connected
      internal: true
      id: wifi_ip_addr
      name: "IP Address"

uart:
  id: mod_bus
  tx_pin: GPIO38
  rx_pin: GPIO40
  baud_rate: 9600
  data_bits: 8
  stop_bits: 1
  parity: NONE
  debug: 

modbus:
  id: modbus1
  uart_id: mod_bus
  send_wait_time: 500ms
  flow_control_pin: GPIO36

modbus_controller:
  - id: qd
    # address: 0x01
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 5s

status_led:
  pin:
    number: GPIO15