substitutions:
  devicename: water-tank-final
  friendly_name: Water tank and well sensor
  device_description:  Water tank and well sensor (Carat 4m3)

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  comment: ${device_description}

esp32:
  board: lolin_s2_mini #Pinout: https://www.wemos.cc/en/latest/s2/s2_mini.html
  variant: esp32s2
  framework:
    type: arduino

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  

# Enable logging
logger: 
  level: VERBOSE
  baud_rate: 0

captive_portal:

api:
  encryption:
    key: !secret api_key

# restart 
button:
  - platform: restart
    name: Restart

sensor:
# Reports how long the device has been powered (in minutes)
  - platform: uptime
    name: Uptime
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes

# water level sensor
# https://esphome.io/components/sensor/modbus_controller.html
  - platform: modbus_controller
    modbus_controller_id: mod_well
    name: "Well water level"
    id: modbus_well_water_level
    register_type: holding
    address: 0x0004
    unit_of_measurement: "cm"
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: mod_tank
    name: "Tank water level"
    id: modbus_tank_water_level
    register_type: holding
    address: 0x0004
    unit_of_measurement: "cm"
    value_type: S_WORD

# Reports the WiFi signal strength
  - platform: wifi_signal
    name: Wifi Signal
    update_interval: 60s

text_sensor:
  - platform: version
    name: ESPHome Version
  - platform: wifi_info
    ip_address: # exposes the IP Address when connected
      internal: true
      id: wifi_ip_addr
      name: "IP Address"

uart:
  - id: uart_well
    tx_pin: GPIO01
    rx_pin: GPIO04
    baud_rate: 9600
    data_bits: 8
    stop_bits: 1
    parity: NONE
    debug: 
  - id: uart_tank
    tx_pin: GPIO40
    rx_pin: GPIO36
    baud_rate: 9600
    data_bits: 8
    stop_bits: 1
    parity: NONE
    debug: 

modbus:
  - id: modbus_well
    uart_id: uart_well
    send_wait_time: 500ms
    flow_control_pin: GPIO02
  - id: modbus_tank
    uart_id: uart_tank
    send_wait_time: 500ms
    flow_control_pin: GPIO38

modbus_controller:
  - id: mod_well
    modbus_id: modbus_well
    setup_priority: -10
    update_interval: 5s
  - id: mod_tank
    modbus_id: modbus_tank
    setup_priority: -10
    update_interval: 5s

status_led:
  pin:
    number: GPIO15